#!/usr/bin/env ruby

site 'http://community.opscode.com/api/v1'

cookbook 'apt'
cookbook 'git'

# external

cookbook 'python-build',
  :git => 'https://github.com/shimizukawa/chef-python-build'

cookbook 'mercurial-env',
  :git => 'https://github.com/shimizukawa/chef-mercurial-env'

cookbook 'shimizukawa-env',
  :git => 'https://github.com/shimizukawa/chef-shimizukawa-env'

cookbook 'texlive'
  :git => 'https://github.com/tk0miya/chef-texlive'
